#/**********************************************************************
#* File Name: drivers/char/diag_w/Makefile
#* 
#* (C) NEC CASIO Mobile Communications, Ltd. 2011
#**********************************************************************/
obj-y += diag_wrapper.o

